<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="8807" started-at="2019-08-02T19:24:02Z" finished-at="2019-08-02T19:24:11Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="8807" started-at="2019-08-02T19:24:02Z" finished-at="2019-08-02T19:24:11Z">
      <class name="tests.OneProduct">
        <test-method status="FAIL" signature="testUserIsAbleToByAProduct()[pri:0, instance:tests.OneProduct@6cea706c]" name="testUserIsAbleToByAProduct" duration-ms="7099" started-at="2019-08-02T19:24:02Z" finished-at="2019-08-02T19:24:10Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at pages.ProductsPage.addProductToCart(ProductsPage.java:72)
at tests.OneProduct.testUserIsAbleToByAProduct(OneProduct.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUserIsAbleToByAProduct -->
        <test-method status="PASS" signature="attachScreenshot()[pri:0, instance:tests.OneProduct@6cea706c]" name="attachScreenshot" is-config="true" duration-ms="592" started-at="2019-08-02T19:24:10Z" finished-at="2019-08-02T19:24:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- attachScreenshot -->
        <test-method status="PASS" signature="closeApp()[pri:0, instance:tests.OneProduct@6cea706c]" name="closeApp" is-config="true" duration-ms="811" started-at="2019-08-02T19:24:10Z" finished-at="2019-08-02T19:24:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- tests.OneProduct -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
